### ISSUE TITLE
Publish blog with Github Pages

### ISSUE THREAD

**Issue by katauber** [metafacture/metafacture-blog#3]
Publish blog with Github Pages via Github Actions with every push to main.

Functional review: @acka47 
Code review: @fsteeg

**Comment by katauber** [comment]
Deployed to https://metafacture.github.io/metafacture-blog/

**Comment by acka47** [comment]
I like the general look and the RSS feed is working fine. 

Reading this again, I have some suggestions for improvement of the content:

- Currently it reads: "This blog is maintained by Open Infrastructure team of North Rhine-Westphalian Library Service Centre (hbz)." Couldn't we just write "This blog is maintained by the Metafacture community"?
- Similarly, we should write on the "About" page: "Since 2019 Metafacture is maintained by the Open Infrastructure team, hbz NRW, with contributions from the community."
-  Is the "Extensions" link in the footer necessary? The page will be linked from metafacture.org so that we can remove it I think.

**Comment by katauber** [comment]
Deployed again to https://metafacture.github.io/metafacture-blog/ with the requested changes.

**Comment by acka47** [comment]
I suggestd a typo-fix at https://github.com/metafacture/metafacture-blog/pull/6/files#r703356707. Otherwise this looks fine. +1
